import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[window]
opacity = 1.0

[font]
normal = { family = "FiraMono Nerd Font", style = "Regular" }
size = 16

[cursor]
style = { shape = "Block", blinking = "Never" }
