
[window]
opacity = 0.9

[font]
normal = { family = "FiraMono Nerd Font", style = "Regular" }
size = 12

[cursor]
style = { shape = "Block", blinking = "Never" }

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
